name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.1
  dartx: ^1.1.0
  equatable: ^2.0.5
  game_repository:
    path: ../game_repository
  json_annotation: ^4.7.0
  meta: ^1.8.0
  time: ^2.1.3

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.5.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
